def get_dicionario():
    return {
            501:[
                '77812196000143',
                {
                    14:{
                        'NF':{
                            'corrente':74,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':74,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    51:{
                        'NF':{
                            'corrente':31,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':31,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    77:{
                        'NF':{
                            'corrente':74,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':74,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    78:{
                        'NF':{
                            'corrente':74,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':74,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                }
            ],
            502:[
                '25540652000140',
                {
                    14:{
                        'NF':{
                            'corrente':76,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':76,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    15:{
                        'NF':{
                            'corrente':7,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':7,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    76:{
                        'NF':{
                            'corrente':76,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':76,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    77:{
                        'NF':{
                            'corrente':76,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':76,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                }
            ],
            505:[
                '30125408000150',
                {
                    14:{
                        'NF':{
                            'corrente':82,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':82,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    55:{
                        'NF':{
                            'corrente':30,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':30,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    70:{
                        'NF':{
                            'corrente':59,
                            'historico':242,
                            'contabil':142
                        }
                    },
                    72:{
                        'NF':{
                            'corrente':68,
                            'historico':242,
                            'contabil':142
                        }
                    },
                    73:{
                        'NF':{
                            'corrente':87,
                            'historico':242,
                            'contabil':142
                        }
                    },
                    71:{
                        'NF':{
                            'corrente':57,
                            'historico':1002,
                            'contabil':142
                        }
                    },
                    77:{
                        'NF':{
                            'corrente':82,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':82,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    68:{
                        'NF':{
                            'corrente':58,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':58,
                            'historico':5334,
                            'contabil':5334
                        }
                    },
                    80:{
                        'NF':{
                            'corrente':82,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':82,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    81:{
                        'NF':{
                            'corrente':84,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':84,
                            'historico':5334,
                            'contabil':5334
                        }
                    },
                }
            ],    
            567:[
                '03446938000128',
                {
                    14:{
                        'NF':{
                            'corrente':78,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':78,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    67:{
                        'NF':{
                            'corrente':10,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':10,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    77:{
                        'NF':{
                            'corrente':78,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':78,
                            'historico':439,
                            'contabil':5334
                        }
                    }
                }
            ],
            575:[
                '49326413000150',
                {
                    14:{
                        'NF':{
                            'corrente':80,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':80,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    75:{
                        'NF':{
                            'corrente':65,
                            'historico':1002,
                            'contabil':142
                        },
                        'A':{
                            'corrente':65,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    77:{
                        'NF':{
                            'corrente':80,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':80,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                    79:{
                        'NF':{
                            'corrente':80,
                            'historico':294,
                            'contabil':142
                        },
                        'A':{
                            'corrente':80,
                            'historico':439,
                            'contabil':5334
                        }
                    },
                }
            ],
        }

def get_filial():
    return {
        501:[1,1],
        502:[2,2],
        505:[5,7677],
        567:[3,3],
        575:[7,10751],
    }
