from django.db import models
from relatorios.models import ClassificacaoServicos

class EmpresasOmie(models.Model):
    codigo_cliente_omie = models.CharField(primary_key=True, max_length=255)
    escritorio = models.CharField(max_length=10)
    cd_empresa = models.CharField(max_length=6)
    estab = models.CharField(max_length=2)
    name_empresa = models.CharField(max_length=255)
    cnpj_cpf = models.CharField(max_length=28)
    email = models.CharField(max_length=255, blank=True, null=True)
    
class DepartamentosControle(models.Model):
    nome_departamento = models.CharField(max_length=255, unique=True)

class Servico(models.Model):
    cd_servico = models.CharField(max_length=7, primary_key=True)
    name_servico = models.CharField(max_length=255)
    tipo_servico = models.ForeignKey(ClassificacaoServicos, on_delete=models.SET(""), blank=True, null=True)
    departamentos = models.ManyToManyField(DepartamentosControle, related_name="departamentos")
    considera_custo = models.BooleanField(default=False)
    ativo = models.BooleanField(default=True)
    classificacao = models.CharField(max_length=255, blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True)

class OrdemServico(models.Model):
    departamento = models.CharField(max_length=255)
    cd_servico = models.CharField(max_length=20, blank=True, null=True)
    servico = models.CharField(max_length=255)
    ds_servico = models.CharField(max_length=255)
    observacoes_servico = models.TextField(blank=True, null=True)
    data_realizado = models.DateField()
    data_cobranca = models.DateField()
    quantidade = models.IntegerField(default=0)
    hora_trabalho = models.CharField(max_length=10)
    valor = models.FloatField()
    autorizado_pelo_cliente = models.BooleanField(default=False)
    type_solicitacao = models.CharField(max_length=30)
    solicitado = models.CharField(max_length=255)
    executado = models.CharField(max_length=255)
    criador_os = models.CharField(max_length=255)
    arquivado = models.BooleanField(default=False)
    empresa = models.ForeignKey(EmpresasOmie, on_delete=models.CASCADE)
    cod_os_omie = models.CharField(max_length=50, null=True, default=None)

class OrdemServicoProvisoria(models.Model):
    departamento = models.CharField(max_length=255)
    cd_servico = models.CharField(max_length=50, blank=True, null=True, default=None)
    servico = models.CharField(max_length=255)
    ds_servico = models.CharField(max_length=255)
    observacoes_servico = models.TextField(blank=True, null=True)
    cd_empresa = models.CharField(max_length=50)
    nome_empresa = models.CharField(max_length=255)
    data_realizado = models.DateField()
    data_cobranca = models.DateField()
    quantidade = models.IntegerField(default=0)
    hora_trabalho = models.CharField(max_length=10)
    valor = models.FloatField()
    autorizado_pelo_cliente = models.BooleanField(default=False)
    type_solicitacao = models.CharField(max_length=30)
    solicitado = models.CharField(max_length=255)
    executado = models.CharField(max_length=255)
    criador_os = models.CharField(max_length=255)
    arquivado = models.BooleanField(default=False)
    os_criada = models.BooleanField(default=False)
